### PR TITLE
restore full context of SyntaxErrors

### PR DESCRIPTION
**Pull request by diclophis**
@jrolfs / @sstephenson ... this should restore the full context of the coffeescript compilation error, however, it should be noted that it no longer specifically says "SyntaxError" ...

### CODE REVIEW

**Comment by diclophis** [comment]
@rafaelfranca have any luck reviewing this PR?

**Comment by rafaelfranca** [comment]
Could you show the message before and how it looks now?

**Comment by diclophis** [comment]
With `coffee-script-source v1.9` and above the error message for the given bit of coffeescript looks like so

### example 1

```
    sayHello = ->
      console.log "hello, world"
      unless
```

### example 2

```
    class Foo
      registerSharedBehavior 'tooltips behavior', (options) ->
        tooltipText = opti[]ons.tooltipText
        lineClamp = options.lineClamp ? false
```

### without patch example 1

```
SyntaxError: [stdin]:3:11: unexpected unless
```

### without patch example 1

```
SyntaxError: [stdin]:3:32: unexpected ]
```

### with patch example 2

```
[stdin]:3:11: error: unexpected unless
          unless
          ^^^^^^
```

### with patch example 2

```
[stdin]:3:32: error: unexpected ]
            tooltipText = opti[]ons.tooltipText
                               ^
```

**Comment by diclophis** [comment]
@rafaelfranca bump

**Comment by diclophis** [comment]
@guilleiguaran bump...

**Comment by diclophis** [comment]
@rafaelfranca any chance you could take a look at this PR and make a final call on it?

Thank you

**Comment by rafaelfranca** [comment]
Can you rebase it?

**Comment by diclophis** [comment]
@rafaelfranca I believe i have successfully rebased it, please consider this for mergination.

Thanks again!

**Comment by diclophis** [comment]
@rafaelfranca I think I have all the items crossed off the list, please let me know if there is anything remaining that would block this PR from being merged.

**Pull request closed without merging**
